name: Build MacOS Monterey

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
  push:
    branches:
       - main
       - build-qt-from-source
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


jobs:
  build-macos:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Prepare MacPorts
      run: |
           brew install --only-dependencies qt@6
           brew install ccache

    - name: Configure QT6
      run: |
           ./configure -- -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"

    - name: Build QT6
      run: |
           cmake --build . --parallel

    - name: Install QT6
      run: |
           sudo cmake --install .

    - name: Prepare packages
      run: |
          mkdir ~/artifacts/pkg
          for i in $(find /opt/local -name *.pkg)
          do
          cp $i ~/artifacts/pkg
          done

    - name: QT6 universal
      uses: actions/upload-artifact@v3.0.0
      with:
        name: qt6-universal-macports
        path: ~/artifacts/

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}
      with:
          limit-access-to-actor: true
          #install-dependencies: false
#      timeout-minutes: 60

