name: Build MacOS Monterey

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
  push:
    branches:
       - main
       - linux-toolchain
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


jobs:
  build-linux:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare env
      run: |
           cp scripts/aqt/set_env.sh ~/.aqt_set_env
           echo "source \${HOME}/.aqt_set_env" >> ~/.bashrc
           source ~/.bashrc

    - name: Install dependencies
      run: sudo apt-get install -y openssh-client ca-certificates curl python3 locales clang genisoimage

    - name: Get Qt
      run: |
           source ~/.bashrc
           echo "get QT"
           ./scripts/aqt/get_qt.sh

    - name: Get osxcross
      run: |
           source ~/.bashrc
           echo "get osxcross"
           ./scripts/aqt/get_osxcross.sh

    - name: Install packages
      run: |
           source ~/.bashrc
           echo "install packages"
           ./scripts/aqt/install_packages.sh

    - name: Prepare artifacts
      run: |
           mkdir ~/artifacts
           tar -czf ~/artifacts/aqt-linux.tar.gz $QT_PATH

    - name: Upload artifacts
      uses: actions/upload-artifact@v3.0.0
      with:
        name: aqt-linux
        path: ~/artifacts/

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}
      with:
          limit-access-to-actor: true
          #install-dependencies: false
      timeout-minutes: 60

