name: Build MacOS Monterey

on:
  push:
    branches:
       - main
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


jobs:
  build-macos:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Fetch dependencies
      run: |
           ${{github.workspace}}/scripts/ci/macos/fetch_deps.sh
           
    - name: Check files
      run: |
           mkdir ~/diagnostic-artifacts
           find ~/brew-mod/ > ~/diagnostic-artifacts/brew-mod-contents.txt
    
    - name: Upload diagnostics
      uses: actions/upload-artifact@v3.0.0
      with:
        name: macos-diagnostics
        path: ~/diagnostic-artifacts/
        
    - name: Create universal
      run: |
           mkdir ~/brew-mod || echo "Dir ~/brew-mod/ already created"
           cd ~/brew-mod
           ${{github.workspace}}/scripts/ci/macos/convert_to_universal.sh ~/brew-mod
           rm -Rf ~/brew-mod/{arm64,x86_64}
           
    - name: Prepare Artifact
      run: |
           cd ~/brew-mod
           mv universal brew-monterey-universal
           


    - name: Upload tuningTrainer-mac
      uses: actions/upload-artifact@v3.0.0
      with:
        name: brew-monterey-universal
        path: ~/brew-mod
        
