name: Run MacOS

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
#  push:
#    branches:
#       - main
#       - build-qt-from-source
#  pull_request:
#    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


jobs:
  build-macos:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: mkdir ~/artifacts || echo "~/artifacts already created"

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
          limit-access-to-actor: true
          #install-dependencies: false
      timeout-minutes: 60

    - name: Upload files
      uses: actions/upload-artifact@v3.0.0
      with:
        name: interactiveWorkflowFiles
        path: ~/artifacts/



